<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit971d06c9e644a4cdcdcaa664dd803919
{
    public static $files = array (
        'f9e7778b01e598acdf00361562d45920' => __DIR__ . '/..' . '/advanced-ads/framework/src/assets.php',
    );

    public static $classMap = array (
        'AdvancedAds\\Framework\\Form\\Field' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field.php',
        'AdvancedAds\\Framework\\Form\\Field_Checkbox' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-checkbox.php',
        'AdvancedAds\\Framework\\Form\\Field_Color' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-color.php',
        'AdvancedAds\\Framework\\Form\\Field_Position' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-position.php',
        'AdvancedAds\\Framework\\Form\\Field_Radio' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-radio.php',
        'AdvancedAds\\Framework\\Form\\Field_Size' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-size.php',
        'AdvancedAds\\Framework\\Form\\Field_Text' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-text.php',
        'AdvancedAds\\Framework\\Form\\Field_Textarea' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-field-textarea.php',
        'AdvancedAds\\Framework\\Form\\Form' => __DIR__ . '/..' . '/advanced-ads/framework/src/form/class-form.php',
        'AdvancedAds\\Framework\\Installation\\Install' => __DIR__ . '/..' . '/advanced-ads/framework/src/installation/class-install.php',
        'AdvancedAds\\Framework\\Interfaces\\Initializer_Interface' => __DIR__ . '/..' . '/advanced-ads/framework/src/interfaces/interface-initializer.php',
        'AdvancedAds\\Framework\\Interfaces\\Integration_Interface' => __DIR__ . '/..' . '/advanced-ads/framework/src/interfaces/interface-integration.php',
        'AdvancedAds\\Framework\\Interfaces\\Routes_Interface' => __DIR__ . '/..' . '/advanced-ads/framework/src/interfaces/interface-routes.php',
        'AdvancedAds\\Framework\\JSON' => __DIR__ . '/..' . '/advanced-ads/framework/src/class-json.php',
        'AdvancedAds\\Framework\\Loader' => __DIR__ . '/..' . '/advanced-ads/framework/src/class-loader.php',
        'AdvancedAds\\Framework\\Updates' => __DIR__ . '/..' . '/advanced-ads/framework/src/class-updates.php',
        'AdvancedAds\\Framework\\Utilities\\Arr' => __DIR__ . '/..' . '/advanced-ads/framework/src/utilities/class-arr.php',
        'AdvancedAds\\Framework\\Utilities\\Params' => __DIR__ . '/..' . '/advanced-ads/framework/src/utilities/class-params.php',
        'AdvancedAds\\Genesis\\Admin' => __DIR__ . '/../..' . '/includes/admin/class-admin.php',
        'AdvancedAds\\Genesis\\Frontend' => __DIR__ . '/../..' . '/includes/class-frontend.php',
        'AdvancedAds\\Genesis\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit971d06c9e644a4cdcdcaa664dd803919::$classMap;

        }, null, ClassLoader::class);
    }
}
