<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit320dcf7366f09e5e42eae6f3414888e8
{
    public static $classMap = array (
        'AdvancedAds\\Framework\\Interfaces\\WordPress_Integration' => __DIR__ . '/..' . '/advanced-ads/framework/src/interfaces/interface-wordpress-integration.php',
        'AdvancedAds\\Framework\\JSON' => __DIR__ . '/..' . '/advanced-ads/framework/src/class-json.php',
        'AdvancedAds\\Framework\\Updates' => __DIR__ . '/..' . '/advanced-ads/framework/src/class-updates.php',
        'AdvancedAds\\Framework\\Utilities\\Arr' => __DIR__ . '/..' . '/advanced-ads/framework/src/utilities/class-arr.php',
        'AdvancedAds\\Framework\\Utilities\\Params' => __DIR__ . '/..' . '/advanced-ads/framework/src/utilities/class-params.php',
        'AdvancedAds\\Genesis\\Admin' => __DIR__ . '/../..' . '/includes/admin/class-admin.php',
        'AdvancedAds\\Genesis\\Frontend' => __DIR__ . '/../..' . '/includes/class-frontend.php',
        'AdvancedAds\\Genesis\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit320dcf7366f09e5e42eae6f3414888e8::$classMap;

        }, null, ClassLoader::class);
    }
}
