<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\Genesis\\Admin' => $baseDir . '/includes/admin/class-admin.php',
    'AdvancedAds\\Genesis\\Autoloader' => $baseDir . '/includes/class-autoloader.php',
    'AdvancedAds\\Genesis\\Frontend' => $baseDir . '/includes/class-frontend.php',
    'AdvancedAds\\Genesis\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
