<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\Framework\\Assets_Registry' => $vendorDir . '/advanced-ads/framework/src/class-assets-registry.php',
    'AdvancedAds\\Framework\\Form\\Field' => $vendorDir . '/advanced-ads/framework/src/form/class-field.php',
    'AdvancedAds\\Framework\\Form\\Field_Checkbox' => $vendorDir . '/advanced-ads/framework/src/form/class-field-checkbox.php',
    'AdvancedAds\\Framework\\Form\\Field_Color' => $vendorDir . '/advanced-ads/framework/src/form/class-field-color.php',
    'AdvancedAds\\Framework\\Form\\Field_Position' => $vendorDir . '/advanced-ads/framework/src/form/class-field-position.php',
    'AdvancedAds\\Framework\\Form\\Field_Radio' => $vendorDir . '/advanced-ads/framework/src/form/class-field-radio.php',
    'AdvancedAds\\Framework\\Form\\Field_Selector' => $vendorDir . '/advanced-ads/framework/src/form/class-field-selector.php',
    'AdvancedAds\\Framework\\Form\\Field_Size' => $vendorDir . '/advanced-ads/framework/src/form/class-field-size.php',
    'AdvancedAds\\Framework\\Form\\Field_Switch' => $vendorDir . '/advanced-ads/framework/src/form/class-field-switch.php',
    'AdvancedAds\\Framework\\Form\\Field_Text' => $vendorDir . '/advanced-ads/framework/src/form/class-field-text.php',
    'AdvancedAds\\Framework\\Form\\Field_Textarea' => $vendorDir . '/advanced-ads/framework/src/form/class-field-textarea.php',
    'AdvancedAds\\Framework\\Form\\Form' => $vendorDir . '/advanced-ads/framework/src/form/class-form.php',
    'AdvancedAds\\Framework\\Installation\\Install' => $vendorDir . '/advanced-ads/framework/src/installation/class-install.php',
    'AdvancedAds\\Framework\\Interfaces\\Initializer_Interface' => $vendorDir . '/advanced-ads/framework/src/interfaces/interface-initializer.php',
    'AdvancedAds\\Framework\\Interfaces\\Integration_Interface' => $vendorDir . '/advanced-ads/framework/src/interfaces/interface-integration.php',
    'AdvancedAds\\Framework\\Interfaces\\Routes_Interface' => $vendorDir . '/advanced-ads/framework/src/interfaces/interface-routes.php',
    'AdvancedAds\\Framework\\JSON' => $vendorDir . '/advanced-ads/framework/src/class-json.php',
    'AdvancedAds\\Framework\\Loader' => $vendorDir . '/advanced-ads/framework/src/class-loader.php',
    'AdvancedAds\\Framework\\Notices\\Manager' => $vendorDir . '/advanced-ads/framework/src/notices/class-manager.php',
    'AdvancedAds\\Framework\\Notices\\Notice' => $vendorDir . '/advanced-ads/framework/src/notices/class-notice.php',
    'AdvancedAds\\Framework\\Notices\\Storage' => $vendorDir . '/advanced-ads/framework/src/notices/class-storage.php',
    'AdvancedAds\\Framework\\Updates' => $vendorDir . '/advanced-ads/framework/src/class-updates.php',
    'AdvancedAds\\Framework\\Utilities\\Arr' => $vendorDir . '/advanced-ads/framework/src/utilities/class-array.php',
    'AdvancedAds\\Framework\\Utilities\\Formatting' => $vendorDir . '/advanced-ads/framework/src/utilities/class-formatting.php',
    'AdvancedAds\\Framework\\Utilities\\Params' => $vendorDir . '/advanced-ads/framework/src/utilities/class-params.php',
    'AdvancedAds\\Framework\\Utilities\\Str' => $vendorDir . '/advanced-ads/framework/src/utilities/class-string.php',
    'AdvancedAds\\Genesis\\Admin' => $baseDir . '/includes/admin/class-admin.php',
    'AdvancedAds\\Genesis\\Frontend' => $baseDir . '/includes/class-frontend.php',
    'AdvancedAds\\Genesis\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
