<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'AdvancedAds\\Framework\\Interfaces\\WordPress_Integration' => $vendorDir . '/advanced-ads/framework/src/interfaces/interface-wordpress-integration.php',
    'AdvancedAds\\Framework\\JSON' => $vendorDir . '/advanced-ads/framework/src/class-json.php',
    'AdvancedAds\\Framework\\Updates' => $vendorDir . '/advanced-ads/framework/src/class-updates.php',
    'AdvancedAds\\Framework\\Utilities\\Arr' => $vendorDir . '/advanced-ads/framework/src/utilities/class-arr.php',
    'AdvancedAds\\Framework\\Utilities\\Params' => $vendorDir . '/advanced-ads/framework/src/utilities/class-params.php',
    'AdvancedAds\\Genesis\\Admin' => $baseDir . '/includes/admin/class-admin.php',
    'AdvancedAds\\Genesis\\Frontend' => $baseDir . '/includes/class-frontend.php',
    'AdvancedAds\\Genesis\\Plugin' => $baseDir . '/includes/class-plugin.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
