<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit06a503665edb0f34061882affc4437de
{
    public static $classMap = array (
        'AdvancedAds\\Genesis\\Admin' => __DIR__ . '/../..' . '/includes/admin/class-admin.php',
        'AdvancedAds\\Genesis\\Autoloader' => __DIR__ . '/../..' . '/includes/class-autoloader.php',
        'AdvancedAds\\Genesis\\Frontend' => __DIR__ . '/../..' . '/includes/class-frontend.php',
        'AdvancedAds\\Genesis\\Plugin' => __DIR__ . '/../..' . '/includes/class-plugin.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit06a503665edb0f34061882affc4437de::$classMap;

        }, null, ClassLoader::class);
    }
}
